Repository obss/jury, pull requests merged in 2021-08, with the labels that each got.

#35 New metrics structure completed.
  .github/workflows/ci.yml
  jury/collator.py
  jury/core.py
  jury/definitions.py
  jury/metrics/__init__.py
  jury/metrics/_base.py
  jury/metrics/bertscore.py
  jury/metrics/bleu.py
  jury/metrics/meteor.py
  jury/metrics/rouge.py
  jury/metrics/sacrebleu.py
  jury/metrics/squad.py
  jury/tokenizer.py
  jury/utils.py
  setup.py
  tests/jury/__init__.py
  tests/jury/metrics/__init__.py
  tests/jury/metrics/test_bertscore.py
  tests/jury/metrics/test_bleu.py
  tests/jury/metrics/test_meteor.py
  tests/jury/metrics/test_rouge.py
  tests/jury/metrics/test_sacrebleu.py
  tests/jury/metrics/test_squad.py
  tests/jury/test_jury.py
  tests/run_code_style.py
  tests/run_tests.py
  tests/utils.py
Labels: patch

#41 add colab badge into demo notebook
  examples/jury_evaluate.ipynb
Labels: documentation, enhancement

#42 Bleu input cases handled in compute function.
  jury/core.py
  jury/metrics/_base.py
  jury/metrics/bertscore.py
  jury/metrics/bleu.py
  jury/metrics/sacrebleu.py
  jury/metrics/squad.py
  tests/jury/metrics/test_bleu.py
  tests/jury/metrics/test_sacrebleu.py
  tests/jury/test_jury.py
Labels: enhancement, patch
